config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users

  resources :stuffs do
    resources :bookings, only: [:create, :new]
  end

  resources :bookings, only: [:edit, :index, :destroy, :update]

  resources :bookings do
    member do
      put :accept
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :stuff
  validates :date, presence: true
  validate :user_cannot_be_owner

  private

  def user_cannot_be_owner
    if user == stuff.user
      errors.add(:user, "cannot be the owner of the stuff")
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :stuffs
end

app/models/stuff.rb
class Stuff < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :bookings, dependent: :destroy
  has_one_attached :photos

  def accepted?
    bookings.exists?(accepted: true)
  end

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :stuffs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])


    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @my_bookings = current_user.bookings
    @my_stuff_booked = Booking.joins(:stuff).where("stuffs.user_id = ?", current_user.id)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @stuff = Stuff.find(params[:stuff_id])

    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @booking.stuff_id = @stuff.id

    if !@stuff.bookings.where(date: @booking.date).empty?
      return redirect_to stuff_path(@stuff), flash: {alert: "Cet équipement est déjà réservé à cette date."}
    end

    if @booking.save
      return redirect_to bookings_path
    else
      redirect_to stuff_path(@stuff), flash: {alert: @booking.errors}
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
    redirect_to bookings_path(@bookings), notice: "La réservation a été modifiée avec succès"
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.accepted = true

    if @booking.save
      redirect_to bookings_path, notice: "La réservation a été validée avec succès"
    else
      redirect_to bookings_path
    end
  end

private

  def booking_params
    params.require(:booking).permit(:date, :user_id, :stuff_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/stuffs_controller.rb
class StuffsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @stuffs = Stuff.all
    @markers = @stuffs.geocoded.map do |stuff|
      {
        lat: stuff.latitude,
        lng: stuff.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {stuff: stuff}),
        marker_html: render_to_string(partial: "marker", locals: {stuff: stuff})
      }
    end
  end

  def show
    @stuff = Stuff.find(params[:id])
    @category_name = Category.find(@stuff.category_id).name.to_s
    @booking = Booking.new
  end

  def edit
    @stuff = Stuff.find(params[:id])
  end

  def update
    @stuff = Stuff.find(params[:id])
    if @stuff.update(stuff_params)
    redirect_to stuffs_path(@stuffs), flash: {alert: "L'équipement a été modifié avec succès"}
    else
      render :edit
    end
  end

  def new
    @stuff = Stuff.new
  end

  def create
    @stuff = Stuff.new(stuff_params)
    @stuff.user_id = current_user.id
    if @stuff.save
      return redirect_to stuffs_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @stuff = Stuff.find(params[:id])
    @stuff.destroy
    redirect_to stuffs_path, status: :see_other
  end

  private

  def stuff_params


    params.require(:stuff).permit(:name, :price, :category_id, :adress,:current_user, photos: [], :description)



  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/delete.html.erb
<h1>Bookings#delete</h1>
<p>Find me in app/views/bookings/delete.html.erb</p>

app/views/bookings/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Modifier la réservation</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>
  <h1>Modifier la réservation</h1>

  <%= simple_form_for @booking, url: booking_path(@booking), method: :patch do |form| %>
    <% if @booking.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
        <ul>
          <% @booking.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.input :date %>
    </div>x

    <div>
      <%= form.submit "Modifier la réservation" %>
    </div>
  <% end %>

  <%= link_to "Retour", bookings_path %>
</body>
</html>

app/views/bookings/index.html.erb
<div class="contain">
  <h1>Dashboard</h1>
  <div class="section">
    <h2>Mes équipements réservés</h2>
    <% @my_stuff_booked.each do |booking| %>
      <div class="booking-card">
        <p class="booking-info">Equipements : <%= booking.stuff.name %></p>
        <p class="booking-info">DATE : <%= booking.date %></p>
        <p class="booking-info">Nom : <%= booking.user.first_name %></p>
        <p class="booking-info">Prix : <%= booking.stuff.price %></p>

        <% if booking.accepted == nil  %>
          <p>Statut : En attente</p>
          <%= link_to "Valider la réservation", accept_booking_path(booking), data: {turbo_method: :put}, class: "btn-primary" %>

        <% elsif booking.accepted %>
          <p>Statut : Acceptée</p>
        <% else %>
          <p>Statut : Refusé</p>
        <% end %>

      </div>
    <% end %>
  </div>

  <div class="section">
    <h2>Mes équipements</h2>
    <ul class="equipment-list">
      <% current_user.stuffs.each do |stuff|%>
        <li class="equipment-item">
          <span class="equipment-name"><%= stuff.name %></span>
            <%= link_to "Edit", edit_stuff_path(stuff), class: "btn-primary" %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="section">
    <h2>Vos réservations</h2>
    <% @my_bookings.each do |booking| %>
      <div class="booking-card">

        <p>Pour <%= booking.user.first_name %> <%= booking.user.last_name %> :</p>
        <p><%= booking.stuff.name %> <%= booking.date %></p>
        <% if booking.accepted == nil  %>
        <p>Statut : En attente</p>
        <% elsif booking.accepted %>
        <p>Statut : Acceptée</p>
        <% else %>
        <p>Statut : Refusé</p>
        <% end %>
        <div class="booking-actions">
          <%= link_to "Edit",  edit_booking_path(booking), class: "btn-secondary" %>
          <%= link_to "Delete", booking_path(booking.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn-danger" %>
        </div>
      </div>
    <% end %>

    <div class="section">
      <p><%= link_to "Retour",  stuffs_path, class: "btn-secondary" %></p>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>Nouvelle réservation</h1>

<div class="card">
  <div class="card-header">
    <div class="text-header">Nouvelle réservation</div>
  </div>
  <div class="card-body">
<%= simple_form_for @booking, url: stuff_bookings_path(@stuff_id), method: :post do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> </h2>
      <ul>
        <% @booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :date %>


  <div class="actions">
    <%= f.button :submit, 'Reserve' %>
  </div>
<% end %>
     <input type="submit" class="btn" value="submit">    </form>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentSports</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body data-controller="navbar">

    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
  <section class="header-section">
    <div class="container1">
        <div class="row">
            <div class="col">
                <h1> Trouver votre nouveau Sport!</h1>
                <p>Le Succès n'est toujours pas une question de grandeur,<br> c'est une question de pratique, un travail acharné pour cela notre site vous propose la location d'équipement sportif afin de performer dans le domaine <br> Sportif</p>
                <div class="bouton_home">
                <%= link_to "Explorez Maintenant", stuffs_path %>
                </div>
            </div>
            <div class="col">
              <%= cl_image_tag ('https://res.cloudinary.com/dc3ixejlq/image/upload/v1685622932/zejaxryt7uirodw7xbid.jpg') %>
            </div>
        </div>
    </div>
  </section>

<section class="future-produits">
  <h2> Meilleurs Produits</h2>
    <div class="rowII">
      <div class="col-4">
        <div class="icone">
          <%= cl_image_tag ('https://res.cloudinary.com/dc3ixejlq/image/upload/w_1000,ar_16:9,c_fill,g_auto,e_sharpen/v1685622762/skbjivopb6yj7sgq1isq.jpg') %>
          <h3>Ball de Base-ball</h3>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
          <p>Prix: 5000€ la journée</p>
        </div>
      </div>
        <div class="col-4">
          <div class="icone">
          <%= cl_image_tag ('https://res.cloudinary.com/dc3ixejlq/image/upload/w_1000,ar_16:9,c_fill,g_auto,e_sharpen/v1685622885/z1pturesnq0cwj5ru0de.jpg') %>
          <h3>Gant de boxe</h3>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <p>Prix: 2000€ la journée</p>
          </div>
        </div>
          <div class="col-4">
            <div class="icone">
            <%= cl_image_tag ('https://res.cloudinary.com/dc3ixejlq/image/upload/v1685622861/hirxf8f4qfueddo4vels.jpg') %>
            <h3>Ballon américain</h3>
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
            <p>Prix: 1000€ la journée</p>
           </div>
          </div>
            <div class="col-4">
              <div class="icone">
              <%= cl_image_tag ('https://res.cloudinary.com/dc3ixejlq/image/upload/v1685622900/cw7wfqpvlskxfrpqmjzs.jpg') %>
              <h3>Matériel cardio</h3>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
              <p>1000€ la journée</p>
              </div>
            </div>
        </div>
</section>

app/views/shared/_navbar.html.erb
<header class="navbar">
        <div class="corps">
          <div class="Sourcelogo" data-action="click->navbar#toggleMenu">
            <div class="logomenu"></div>
            <div class="logomenu"></div>
            <div class="logomenu"></div>
          </div>
        </div>
        <ul class="menu" data-navbar-target="menu">
          <li><%= link_to "Produits", stuffs_path %></li>
          <li><%= link_to "Compte", bookings_path %></a></li>
          <% if user_signed_in? %>
            <li>
              <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
            </li>
          <% end %>
        </ul>
      </header>
    <div class="titre">
      <a><strong><%= link_to "Rent-Sports", root_path %></strong></a>
      </div>

app/views/stuffs/_form.html.erb
<%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

<%# <%= f.input :address, input_html: {data: {"..."}, class: "d-none"} %> %>

app/views/stuffs/_info_window.html.erb
<h2><%= stuff.name %></h2>
 <p><%= stuff.address %></p>

app/views/stuffs/_marker.html.erb
 <div class="badge rounded-pill bg-primary fs-6">
  <p> <%= @stuffs.name %></p>
</div>

app/views/stuffs/destroy.html.erb
<h1>Equipments#destroy</h1>
<p>Find me in app/views/equipments/destroy.html.erb</p>

app/views/stuffs/edit.html.erb
<div class="card">
  <div class="card-header">
    <div class="text-header">Fiche d'information</div>

    </div>
    <div class="card-body">
      <%= simple_form_for(@stuff, url:  stuff_path, method: :patch) do |f| %>
      <%= f.input :name %>
      <%= f.input :category_id, collection: Category.all %>
      <%= f.label :price %>
      <%= f.number_field :price %>
      <div>
        <%= f.label :description %>
        <%= f.text_area :description %>

  <%= f.input :description %>
  <%= f.button :submit, 'Mettez à jour votre équipement', class: 'btn-edit'  %>
<% end %>

      </div>
    <div>
  </div>
</div>
<div>
  <input type="submit" class="btn-edit" value=" Mettre à jour la fiche d'information">
  <% end %>
</div>

app/views/stuffs/index.html.erb
<div class="mb">
  <h3>Produits</h3>
  <%= link_to "louez votre équipement", new_stuff_path, class: "btn_index" %>
</div>
<div class="d-flex">
  <div class="row w-50">
    <% @stuffs.each do |stuff| %>
    <% unless stuff.user == current_user %>
      <div class="col-6 mx-auto">
      <%= link_to stuff_path(stuff) do %>
      <%= image_tag '' %>
        <div class="card-category">
          <%= stuff.name %>
            <div class="icone">
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
            </div>
            <p>Prix: <%= stuff.price %>€ la journée</p>
        </div>
        <% end %>
  </div>
  <% end %>
  <% end %>
</div>

<div class="w-50 col-lg-4">
  <div class="map col sticky-top" style="height: 100vh">
    <div style="width: 100%; height: 600px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        <div id="map">
        </div>
    </div>
  </div>
    <div style="height: 100%;">
      <div class="show-rows">
        <div class="show-row" *ngFor="let show of shows; let i=index">
          <div #spacer></div>
            <div stickyThing [spacer]="spacer">
              <div #map style="width: 50%; height:100%; position: fixed; left: 500px;" [ngStyle]="{'height': getViewPortHeight()}"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stuffs/new.html.erb
<div class="card">
  <div class="card-header">
    <div class="text-header">Mettez en location votre équipement</div>
    </div>
  <div class="card-body">
    <%= simple_form_for(@stuff, url: stuffs_path, method: :post) do |f| %>
    <%= f.input :name %>
    <%= f.input :category_id, collection: Category.all %>
    <%= f.input :price %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <div>
      <%= f.label :description %>
        <div class="textarea">
          <%= f.text_area :description %>
        </div>
    </div>
    <input type="submit" class="btn-new" value="Louez votre équipement">
    <% end %>
  </div>
</div>

app/views/stuffs/show.html.erb
<%# ------- Réservations ----- %>
<div class="card">
  <div class="card-header">
    <div class="text-header">Réservations</div>
    </div>
    <div class="card-body">
    <%= simple_form_for @booking, url: stuff_bookings_path(@stuff.id), method: :post do |f| %>
    <% if @booking.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@booking.errors.count, "error") %> </h2>
          <ul>
          <% @booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
          </ul>
      </div>
     <% end %>
    <%= f.input :date, as: :date %>
    <h1><%=  @stuff.name%></h1>
    <p>Catégorie: <%= @category_name %></p>
    <p> Année : <%=  @stuff.year%></p>
    <p>Prix: <%=  @stuff.price%></p>
    <p>Description: <%=  @stuff.description%></p>
    <p>Adresse: <%=  @stuff.address%></p>
     <div class="actions">
      <input type="submit" class="btn-new" value="Réservé">
    </div>
    <% end %>
  </div>
</div>

<%# ------- Réservations ----- %>





<%# ------ Alerte message -------- %>
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>
<%# ------ Alerte message -------- %>
<div class="btn-show1">
  <%= link_to "Delete",
    stuff_path(@stuff),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
</div>

<div class="btn-show2">
  <%= link_to "Edit", edit_stuff_path(@stuff)%>
</div>

<div class="btn-show3">
  <%= link_to "Back", stuffs_path %>
</div>

<% @stuff.photos.each do |photo| %>
  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
<% end %>